Update Build
WikiWatershed/mmw-geoprocessing pull request #95
Opened 2021-11-04 16:52 UTC by rajadain

## Overview

This project was not building because of outdated dependencies. This updates them.

## Testing Instructions

* Ensure you have Java 8 installed on your system
    ```console
    brew install java
    ```
* Check out this branch and run `update`
  - [ ] Ensure it succeeds
* Run `server`
* From another tab, send a sample request (using [http](https://httpie.io/) or [xh](https://github.com/ducaale/xh) or curl) to the `/multi` endpoint
    ```console
    http :8090/multi < examples/MultiOperationRequest.json
    ```
  - [ ] Ensure it succeeds

2021-11-04 21:53 UTC, emilyhu0106 requested changes
The build is working successfully, but needs additional setups

1. The build requires Java 8, but `brew install java` is for java 11. Use 
``` 
brew tap adoptopenjdk/openjdk
brew install --cask adoptopenjdk8
```
to install Java 8

2. When I run `update`, I got `The operation couldn't be completed. Unable to locate a Java Runtime.` error after installing Java. Need to install `autoconf` and run
```
sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
```
to successfully run `update`

2021-11-04 21:59 UTC, rajadain commented
Thanks, I created #96 to update the README and reflect those requirements.

2021-11-04 22:01 UTC, rajadain commented
We can't add those steps into a `setup` script because they are macOS specific, and this project could be run on Linux machines as well.

What changes would you like in the code of this PR before it is approved?

2021-11-05 16:34 UTC, emilyhu0106 approved these changes

2021-11-05 16:35 UTC, merged